"""initial registry schema

Revision ID: abdcdc585430
Revises: 
Create Date: 2026-07-24 16:27:50.370870
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdcdc585430'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathway_lock',
    sa.Column('wpid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('held_by', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('wpid')
    )
    op.create_table('review',
    sa.Column('pr_number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('wpid', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CHANGES_REQUESTED', 'MERGED', 'CLOSED', name='reviewstatus', native_enum=False, length=24), nullable=False),
    sa.Column('assigned_curator', sa.String(length=255), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pr_number')
    )
    op.create_table('wpid_reservation',
    sa.Column('wpid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('reserved_by', sa.String(length=255), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RESERVED', 'MERGED', name='reservationstatus', native_enum=False, length=16), nullable=False),
    sa.PrimaryKeyConstraint('wpid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wpid_reservation')
    op.drop_table('review')
    op.drop_table('pathway_lock')
    # ### end Alembic commands ###
